# Cloud Config Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce
  labels:
    app: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: pipebarreto/cloud-config:latest
        ports:
        - containerPort: 9296
        env:
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILIBILITY_ZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery-service:8761/eureka/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery-service:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "cloud-config"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"