# shipping Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: pipebarreto/shipping-service:stage
        ports:
        - containerPort: 8600
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILIBILITY_ZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery-service:8761/eureka/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery-service:8761/eureka/"
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://cloud-config-service:9296
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "shipping-service"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"